model:
  save_dir: 'model'
  batch_size: 64
  gamma: 0.99
  tau: 0.01
  replay_buffer_size: 50000
  num_episodes: 1000
  steps_per_episode: 500

  actor:
    hidden_layers: [256]
    learning_rate: 0.0001
  
  critic: 
    hidden_layers: [256]
    learning_rate: 0.001

test:
  num_episodes: 30